name: Node App CI/CD

on:
  push:
    branches: [ develop, master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
      - name: Install proxy & configure certificates
        run: |
          sudo apt update
          sudo apt install python3-pip
          echo "Installing mitmproxy using pip................."
          pip3 install mitmproxy
          mitmproxy

      - name: Build, tag, and push image
        env:
          IMAGE_TAG: "${{ github.sha }}" 
        run: |
          echo "Building for git branch: $GIT_BRANCH"
          docker build --no-cache -t mitm_proxy_app:$IMAGE_TAG .